export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT = 'LOGOUT';

export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';
export const REGISTRATION_FAIL = 'REGISTRATION_FAIL';

export const QUOTE_ADDED = 'QUOTE_ADDED';
export const QUOTE_ADDED_REFRESH = 'QUOTE_ADDED_REFRESH';
export const QUOTE_NOT_ADDED = 'QUOTE_NOT_ADDED';

export const GET_QUOTES = 'GET_QUOTES';
export const GET_USER_QUOTES = 'GET_USER_QUOTES';
export const GET_QUOTE = 'GET_QUOTE';
export const QUOTE_NOT_FOUND = 'QUOTE_NOT_FOUND';
export const NO_QUOTES_FOUND = 'NO_QUOTES_FOUND';
export const RESET_QUOTES = 'RESET_QUOTES';

export const LOADING_QUOTE = 'LOADING_QUOTE';
export const LOADING_AUTH = 'LOADING_AUTH';

export const QUOTE_DELETED = 'QUOTE_DELETED';
export const QUOTE_NOT_DELETED = 'QUOTE_NOT_DELETED';

export const QUOTE_EDITED = 'QUOTE_EDITED';
export const QUOTE_UPDATE_FAILED = 'QUOTE_UPDATE_FAILED';

export const GET_CURRENT_USER = 'GET_CURRENT_USER';

export const UPDATE_USER = 'UPDATE_USER';
export const USER_UPDATE_FAILED = 'USER_UPDATE_FAILED';

export const GET_USER_BY_USERNAME = 'GET_USER_BY_USERNAME';
export const GET_QUOTES_BY_USERNAME = 'GET_QUOTES_BY_USERNAME';

export const DELETE_USER_IMAGE = 'DELETE_USER_IMAGE';
export const DELETE_USER = 'DELETE_USER';

export const RESET_QUOTE_MESSAGE = 'RESET_QUOTE_MESSAGE';
export const RESET_USER_MESSAGE = 'RESET_USER_MESSAGE';

export const VERIFY_USER_EMAIL = 'VERIFY_USER_EMAIL';
export const RESET_REGISTRATION_SUCCESS = 'RESET_REGISTRATION_SUCCESS';